import { execFile } from 'node:child_process';
import type { ChildProcess, ExecFileException, ExecFileOptions } from 'node:child_process';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import * as vscode from 'vscode';
import {
  resolveYarnFamily,
  yarnVersionProbeMaxBufferBytes,
  yarnVersionProbeTimeoutMs,
} from '../utils';

vi.mock('node:child_process', () => ({
  execFile: vi.fn(),
}));

type ExecFileCallback = NonNullable<Parameters<typeof execFile>[3]>;

const root = '/workspace/project';

function mockWorkspaceFiles(files: Record<string, string>): void {
  vi.mocked(vscode.workspace.fs.readFile).mockImplementation((uri: vscode.Uri) => {
    const value = files[uri.fsPath];
    return value === undefined
      ? Promise.reject(new Error(`File not found: ${uri.fsPath}`))
      : Promise.resolve(Buffer.from(value));
  });
}

function mockVersionProbe(err: unknown, stdout: string): void {
  vi.mocked(execFile).mockImplementationOnce((
    _file: string,
    _args: readonly string[] | null | undefined,
    _options: ExecFileOptions | null | undefined,
    callback: ExecFileCallback | null | undefined,
  ) => {
    if (callback === undefined || callback === null) {
      throw new Error('Expected execFile callback.');
    }
    callback(err as ExecFileException, stdout, '');
    return {} as ChildProcess;
  });
}

describe('resolveYarnFamily()', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockWorkspaceFiles({});
  });

  it.each([
    ['1.22.19', 'classic'],
    ['4.6.0', 'modern'],
    ['2.4.3', 'modern'],
  ] as const)('uses packageManager yarn@%s metadata before any filesystem markers', async (version, family) => {
    mockWorkspaceFiles({
      [`${root}/package.json`]: JSON.stringify({ packageManager: `yarn@${version}` }),
      [`${root}/.yarnrc.yml`]: 'yarnPath: .yarn/releases/yarn.cjs',
      [`${root}/.yarnrc`]: '--install.offline true',
    });

    await expect(resolveYarnFamily(root)).resolves.toEqual({
      family,
      source: 'package-manager',
    });
    expect(execFile).not.toHaveBeenCalled();
  });

  it('recognizes Modern from a same-root .yarnrc.yml marker without metadata', async () => {
    mockWorkspaceFiles({
      [`${root}/package.json`]: JSON.stringify({ name: 'app' }),
      [`${root}/.yarnrc.yml`]: 'nodeLinker: node-modules',
    });

    await expect(resolveYarnFamily(root)).resolves.toEqual({
      family: 'modern',
      source: 'project-markers',
    });
    expect(execFile).not.toHaveBeenCalled();
  });

  it('recognizes Modern from the Berry yarn.lock metadata marker', async () => {
    mockWorkspaceFiles({
      [`${root}/package.json`]: '{}',
      [`${root}/yarn.lock`]: '__metadata:\n  version: 8\n',
    });

    await expect(resolveYarnFamily(root)).resolves.toMatchObject({ family: 'modern' });
    expect(execFile).not.toHaveBeenCalled();
  });

  it('recognizes the Berry yarn.lock metadata marker with CRLF line endings', async () => {
    mockWorkspaceFiles({
      [`${root}/package.json`]: '{}',
      [`${root}/yarn.lock`]: '__metadata:\r\n  version: 8\r\n',
    });

    await expect(resolveYarnFamily(root)).resolves.toEqual({
      family: 'modern',
      source: 'project-markers',
    });
    expect(execFile).not.toHaveBeenCalled();
  });

  it.each([
    ['.yarnrc', '--install.offline true'],
    ['yarn.lock', '# THIS IS AN AUTOGENERATED FILE.\n# yarn lockfile v1\n'],
  ])('recognizes Classic from a same-root %s marker', async (fileName, contents) => {
    mockWorkspaceFiles({
      [`${root}/package.json`]: '{}',
      [`${root}/${fileName}`]: contents,
    });

    await expect(resolveYarnFamily(root)).resolves.toMatchObject({ family: 'classic' });
    expect(execFile).not.toHaveBeenCalled();
  });

  it('returns unknown for conflicting Classic and Modern markers without probing PATH', async () => {
    mockWorkspaceFiles({
      [`${root}/package.json`]: '{}',
      [`${root}/.yarnrc.yml`]: 'nodeLinker: node-modules',
      [`${root}/yarn.lock`]: '# yarn lockfile v1\n',
    });

    await expect(resolveYarnFamily(root)).resolves.toEqual({
      family: 'unknown',
      source: 'conflicting-markers',
    });
    expect(execFile).not.toHaveBeenCalled();
  });

  it.each([
    ['1.22.19\n', 'classic'],
    ['4.6.0\n', 'modern'],
  ] as const)('falls back to a bounded same-root version probe (%s)', async (stdout, family) => {
    mockWorkspaceFiles({ [`${root}/package.json`]: '{}' });
    mockVersionProbe(null, stdout);

    await expect(resolveYarnFamily(root)).resolves.toEqual({
      family,
      source: 'version-probe',
    });
    expect(execFile).toHaveBeenCalledWith(
      'yarn',
      ['--version'],
      {
        cwd: root,
        maxBuffer: yarnVersionProbeMaxBufferBytes,
        timeout: yarnVersionProbeTimeoutMs,
      },
      expect.any(Function),
    );
  });

  it.each([
    ['missing executable', Object.assign(new Error('spawn yarn ENOENT'), { code: 'ENOENT' }), ''],
    ['timed out probe', Object.assign(new Error('timed out'), { killed: true, signal: 'SIGTERM' }), ''],
    ['non-semver output', null, 'unknown version'],
    ['unsupported major zero', null, '0.32.0'],
  ])('keeps the family unknown after a %s', async (_label, err, stdout) => {
    mockWorkspaceFiles({ [`${root}/package.json`]: '{}' });
    mockVersionProbe(err, stdout);

    await expect(resolveYarnFamily(root)).resolves.toEqual({
      family: 'unknown',
      source: 'version-probe',
    });
  });

  it('falls through malformed Yarn metadata to decisive same-root markers', async () => {
    mockWorkspaceFiles({
      [`${root}/package.json`]: JSON.stringify({ packageManager: 'yarn@berry' }),
      [`${root}/.yarnrc.yml`]: 'nodeLinker: node-modules',
    });

    await expect(resolveYarnFamily(root)).resolves.toEqual({
      family: 'modern',
      source: 'project-markers',
    });
  });
});