import type { FixtureFiles, WorkspaceFixture } from './types';

/**
 * Fixture catalogue for the Extension Host integration suite: pure metadata (manifests plus
 * lock files, no `node_modules`, no package manager invocation) so runs stay hermetic and
 * offline. Managers are distinguished the same way `ClientManager.detectPackageManager()`
 * does — `packageManager` field first, then lock file detection — and the `precedence-*` /
 * `no-manager-signals` fixtures combine competing signals to prove that priority order.
 */

interface ManifestOptions {
  readonly packageManager?: string;
  readonly workspaces?: readonly string[];
}

function manifest(name: string, options: ManifestOptions = {}): string {
  const contents: Record<string, unknown> = {
    name,
    version: '1.0.0',
    private: true,
  };

  if (options.packageManager !== undefined) {
    contents.packageManager = options.packageManager;
  }
  if (options.workspaces !== undefined) {
    contents.workspaces = [...options.workspaces];
  }

  contents.dependencies = { 'left-pad': '^1.3.0' };
  contents.devDependencies = { rimraf: '~5.0.5' };

  return `${JSON.stringify(contents, undefined, 2)}\n`;
}

const NPM_LOCK = `${JSON.stringify({
  name: 'nestro-fixture',
  lockfileVersion: 3,
  requires: true,
  packages: {},
}, undefined, 2)}\n`;

const PNPM_LOCK = 'lockfileVersion: \'9.0\'\n\nsettings:\n  autoInstallPeers: true\n  excludeLinksFromLockfile: false\n';

const YARN_CLASSIC_LOCK = '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n';

const YARN_MODERN_LOCK = '__metadata:\n  version: 8\n  cacheKey: 10c0\n';

const YARN_MODERN_RC = 'nodeLinker: node-modules\nenableTelemetry: false\n';

const BUN_LOCK = `${JSON.stringify({
  lockfileVersion: 1,
  workspaces: { '': { name: 'nestro-fixture' } },
  packages: {},
}, undefined, 2)}\n`;

const PNPM_WORKSPACE = 'packages:\n  - \'packages/*\'\n';

function singleRoot(id: string, folder: string, manager: WorkspaceFixture['roots'][number]['manager'], files: FixtureFiles): WorkspaceFixture {
  return {
    id,
    kind: 'single-root',
    files,
    roots: [{ path: folder, manager, manifests: ['package.json'] }],
  };
}

export const SINGLE_ROOT_FIXTURES: readonly WorkspaceFixture[] = [
  singleRoot('npm-single-root', 'npm-app', 'npm', {
    'npm-app/package.json': manifest('npm-app'),
    'npm-app/package-lock.json': NPM_LOCK,
  }),
  singleRoot('pnpm-single-root', 'pnpm-app', 'pnpm', {
    'pnpm-app/package.json': manifest('pnpm-app'),
    'pnpm-app/pnpm-lock.yaml': PNPM_LOCK,
  }),
  singleRoot('yarn-classic-single-root', 'yarn-classic-app', 'yarn', {
    'yarn-classic-app/package.json': manifest('yarn-classic-app'),
    'yarn-classic-app/yarn.lock': YARN_CLASSIC_LOCK,
  }),
  singleRoot('yarn-modern-single-root', 'yarn-modern-app', 'yarn', {
    'yarn-modern-app/package.json': manifest('yarn-modern-app', { packageManager: 'yarn@4.6.0' }),
    'yarn-modern-app/yarn.lock': YARN_MODERN_LOCK,
    'yarn-modern-app/.yarnrc.yml': YARN_MODERN_RC,
  }),
  singleRoot('bun-single-root', 'bun-app', 'bun', {
    'bun-app/package.json': manifest('bun-app'),
    'bun-app/bun.lock': BUN_LOCK,
  }),
  // A genuine Berry project without packageManager metadata: manager detection
  // remains `yarn`, while the audit-family resolver must use same-root markers.
  singleRoot('yarn-modern-no-metadata', 'yarn-modern-no-metadata-app', 'yarn', {
    'yarn-modern-no-metadata-app/package.json': manifest('yarn-modern-no-metadata-app'),
    'yarn-modern-no-metadata-app/yarn.lock': YARN_MODERN_LOCK,
    'yarn-modern-no-metadata-app/.yarnrc.yml': YARN_MODERN_RC,
  }),
  // Contradictory same-root family markers must never silently select Classic
  // or invoke a PATH-dependent audit command.
  singleRoot('yarn-ambiguous-markers', 'yarn-ambiguous-app', 'yarn', {
    'yarn-ambiguous-app/package.json': manifest('yarn-ambiguous-app'),
    'yarn-ambiguous-app/yarn.lock': YARN_CLASSIC_LOCK,
    'yarn-ambiguous-app/.yarnrc.yml': YARN_MODERN_RC,
  }),
  // `packageManager` is checked before any lock file at the same directory
  // (`ClientManager.detectPackageManagerFromManifest` runs first in the ancestor loop) —
  // the yarn.lock here is real and present, and must still lose.
  singleRoot('precedence-field-over-lockfile', 'field-over-lockfile-app', 'pnpm', {
    'field-over-lockfile-app/package.json': manifest('field-over-lockfile-app', { packageManager: 'pnpm@9.1.0' }),
    'field-over-lockfile-app/yarn.lock': YARN_CLASSIC_LOCK,
  }),
  // `detectPackageManagerFromLockfile` checks lock files in a fixed order (pnpm-lock.yaml,
  // yarn.lock, bun.lock/bun.lockb, package-lock.json/npm-shrinkwrap.json) and returns on the
  // first match; these three fixtures stack every lower-priority file behind the winner.
  singleRoot('precedence-pnpm-over-yarn-bun-npm', 'pnpm-wins-app', 'pnpm', {
    'pnpm-wins-app/package.json': manifest('pnpm-wins-app'),
    'pnpm-wins-app/pnpm-lock.yaml': PNPM_LOCK,
    'pnpm-wins-app/yarn.lock': YARN_CLASSIC_LOCK,
    'pnpm-wins-app/bun.lock': BUN_LOCK,
    'pnpm-wins-app/package-lock.json': NPM_LOCK,
  }),
  singleRoot('precedence-yarn-over-bun-npm', 'yarn-wins-app', 'yarn', {
    'yarn-wins-app/package.json': manifest('yarn-wins-app'),
    'yarn-wins-app/yarn.lock': YARN_CLASSIC_LOCK,
    'yarn-wins-app/bun.lock': BUN_LOCK,
    'yarn-wins-app/package-lock.json': NPM_LOCK,
  }),
  singleRoot('precedence-bun-over-npm', 'bun-wins-app', 'bun', {
    'bun-wins-app/package.json': manifest('bun-wins-app'),
    'bun-wins-app/bun.lock': BUN_LOCK,
    'bun-wins-app/package-lock.json': NPM_LOCK,
  }),
  // No manifest field and no lock file anywhere in the ancestor chain: the
  // documented `'npm'` default, exercised explicitly rather than only as an
  // implicit side effect of some other fixture.
  singleRoot('no-manager-signals', 'no-signals-app', 'npm', {
    'no-signals-app/package.json': manifest('no-signals-app'),
  }),
];

/**
 * Two workspace folders whose basename is identical (`app`). Only the parent
 * directory differs, which is the case that breaks any label or lookup keyed on
 * the folder name alone.
 */
const SAME_BASENAME_FIXTURE: WorkspaceFixture = {
  id: 'multi-root-same-basename',
  kind: 'multi-root',
  files: {
    'left/app/package.json': manifest('left-app'),
    'left/app/package-lock.json': NPM_LOCK,
    'right/app/package.json': manifest('right-app'),
    'right/app/pnpm-lock.yaml': PNPM_LOCK,
  },
  roots: [
    { path: 'left/app', manager: 'npm', manifests: ['package.json'] },
    { path: 'right/app', manager: 'pnpm', manifests: ['package.json'] },
  ],
};

/**
 * A workspace folder that carries a manifest at its own root plus nested package manifests,
 * opened next to an unrelated standalone folder. Covers root-manifest discovery and the
 * ancestor walk performed by `ClientManager.detectPackageManager()` for nested packages.
 */
const ROOT_MANIFEST_FIXTURE: WorkspaceFixture = {
  id: 'multi-root-root-manifest',
  kind: 'multi-root',
  files: {
    'monorepo/package.json': manifest('monorepo-root', { workspaces: ['packages/*'] }),
    'monorepo/pnpm-lock.yaml': PNPM_LOCK,
    'monorepo/pnpm-workspace.yaml': PNPM_WORKSPACE,
    'monorepo/packages/api/package.json': manifest('monorepo-api'),
    'monorepo/packages/ui/package.json': manifest('monorepo-ui'),
    'standalone/package.json': manifest('standalone-app'),
    'standalone/bun.lock': BUN_LOCK,
  },
  roots: [
    {
      path: 'monorepo',
      manager: 'pnpm',
      manifests: ['package.json', 'packages/api/package.json', 'packages/ui/package.json'],
    },
    { path: 'standalone', manager: 'bun', manifests: ['package.json'] },
  ],
};

export const MULTI_ROOT_FIXTURES: readonly WorkspaceFixture[] = [
  SAME_BASENAME_FIXTURE,
  ROOT_MANIFEST_FIXTURE,
];

export const WORKSPACE_FIXTURES: readonly WorkspaceFixture[] = [
  ...SINGLE_ROOT_FIXTURES,
  ...MULTI_ROOT_FIXTURES,
];

/** Nested package directory used to assert the manager ancestor walk. */
export const ROOT_MANIFEST_NESTED_PACKAGE = 'packages/ui';