export { AUDIT_PROCESS_MAX_BUFFER_BYTES, AUDIT_PROCESS_TIMEOUT_MS, describeBoundedProcessFailure, mergeSeverity, parseAuditOutcome, parseSeverity, runAuditOutcome, runNpmAudit, runPackageAudit, toAuditResult, UnrecognizedAuditResultError } from './auditClient';
export type { AuditAdvisoriesOutcome, AuditCleanOutcome, AuditErrorOutcome, AuditIncompleteOutcome, AuditIncompleteReason, AuditOutcome, AuditPackageManager, AuditResult, AuditSchemaId, AuditSeverity } from './auditClient';
export { cloneAuditAdvisory, createAuditAdvisory, inferPathAttribution, mergeAttribution, mergeAuditAdvisories, mergePathAttributions } from './auditReport';
export type { AuditAdvisory } from './auditReport';
export { formatAuditReport, validateAdvisoryUrl } from './auditReportFormatter';
export { parseBunAuditOutcome, runBunAudit, runBunAuditOutcome } from './bunAuditClient';
export { parseBunConfig } from './bunConfig';
export { formatDependencySpec, parseDependencySpec } from './dependencySpec';
export type { PinnableDependencySpec } from './dependencySpec';
export { formatAdvisoryRows, formatAuditSeverityLabel, formatDependencySectionLabel, formatFailedPackageFileCount, formatFailedPackageRootCount, formatFilteredPackageCount, formatHeldBackDate, formatPackageCount, formatPackageGroupDescription, formatPackageLevelFindings, formatPackageUpdatesAvailable, formatPinnedPackageVersions, formatUpdateTypeLabel, formatVulnerablePackageCount } from './localization';
export { logger } from './logger';
export { configAwareHttpsMetadataAdapter, fetchPackageMetadata, MetadataAdapterRegistry, resolveMetadataRegistryKey } from './metadataRegistry';
export type { MetadataAdapter, PackageMetadataOutcome } from './metadataRegistry';
export { METADATA_REQUEST_TIMEOUT_MS, METADATA_RESPONSE_MAX_BYTES, runBoundedMetadataRequest } from './metadataRunner';
export type { MetadataSchemaResult } from './metadataRunner';
export { fetchPackageMetadataFromNativeCli, nativeCliMetadataAdapter, parseNativeCliMetadata } from './nativeMetadataClient';
export { fetchAllLatestVersions } from './ncuClient';
export type { NcuUpdateTarget } from './ncuClient';
export { showError } from './notify';
export { CHECK_CONCURRENCY_CAP, createCheckCoordinator, MUTATION_CONCURRENCY_CAP, mutationCoordinator, OperationCoordinator } from './operationCoordinator';
export { buildInstallCommand, buildPackageUpdateCommand, buildRunInstallCommand, detectPackageManager } from './packageManager';
export { getPackageDirectory, pinAllWorkspaceDependencyVersions, readAllWorkspaceDependencies, readWorkspaceDependencies, setVersionPin, switchDependencyType, updateDependencyVersionsInFile, updateDependencyVersionsInFilesAtomically, updateWorkspaceDependencyVersions } from './packageReader';
export type { PackageFileEntries, PackageFileEntry, PackageReadFailure, SkippedPackageFile } from './packageReader';
export { findWorkspacePackageJsonFiles, getWorkspacePackageFilePath, getWorkspacePackageFilePaths, readPackageFile, toWorkspaceRelativePackageFilePath, writeManyPreparedPackageFilesAtomically, writePreparedPackageFile } from './packageRepository';
export type { PreparedPackageFile } from './packageRepository';
export { DependencyTypeConflictError, extractVersionPrefix, parsePackageJson, prepareDependencyType, prepareDependencyVersions, preparePinAllVersions, prepareVersionPin, serializePackageJson, transformDependencyType, transformDependencyVersions, transformPinAllVersions, transformVersionPin, VersionPinConflictError } from './packageTransforms';
export type { PackageFileDependencyUpdates, PackageJsonDocument } from './packageTransforms';
export { getWindowsTaskkillPath, runBoundedProcess } from './processRunner';
export { selectVersionsForPicker } from './registryClient';
export { classifyVersionReleaseAge, DEFAULT_MINIMUM_RELEASE_AGE_DAYS, MAX_MINIMUM_RELEASE_AGE_DAYS, readMinimumReleaseAgeDays, resolveUpdateReleaseAge } from './releaseAge';
export type { ReleaseAgeState } from './releaseAge';
export { runRootOperations, startRootOperations } from './rootOperation';
export { formatShellTaskCommandForLog, formatShellTaskFailureMessage, runShellTaskAndWait } from './shellTask';
export type { ShellTaskCommand } from './shellTask';
export { formatStatusReport } from './statusReport';
export type { StatusReportFailure, StatusReportFileLabel, StatusReportSnapshot } from './statusReport';
export { compareRawVersions, getGreatestVersion, getUpdateType, isPreReleaseVersion, isVersionOutdated } from './versionUtils';
export type { UpdateType } from './versionUtils';
export { parseYarnAuditOutcome, runYarnAudit, runYarnAuditOutcome } from './yarnAuditClient';
export { resolveYarnFamily, yarnVersionProbeMaxBufferBytes, yarnVersionProbeTimeoutMs } from './yarnFamily';
export type { YarnFamily } from './yarnFamily';
export { fetchPackageMetadataFromYarnClassic, fetchPackageMetadataFromYarnModern, parseYarnClassicMetadata, parseYarnModernMetadata, yarnClassicMetadataAdapter } from './yarnMetadataClient';