name: Release

on:
  push:
    branches: [master]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 2. Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*" 
          cache: pnpm

      - name: 3.1 Prepare pnpm
        uses: pnpm/action-setup@v6

      - name: 3.2 Install dependencies
        run: pnpm install

      - name: 4. Check for errors
        run: |
          pnpm type-check
          if [ $? -ne 0 ]; then
            exit 1
          fi

      - name: 5. Build
        run: pnpm run build

      - name: 6. Release
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
